/**
 * @module react/layout/footer
 * @memberof react/layout
 */

import React from 'react'; // `React` must be in scope when using JSX

import registry from '../../lib/componentRegistry';

function footerComponent() {

  return (
    <footer role="contentinfo">
      <p>
        Pages generated by
        <a className="link--plain" href="https://GitHub.com/luxui">Luxui</a>
        ENGINEERED to Amaze, by
        <a className="link--plain" href="http://quickenloans.com">Quicken Loans</a>
      </p>
    </footer>
  );
}
footerComponent.propTypes = {
};

registry('Lux.Layout.Footer', footerComponent, false);
