#! /bin/bash

jest \
  --automock false \
  --collectCoverage true \
  --coverageDirectory "../pages/coverage" \
  --coverageThreshold '{"global":{"branches":100,"functions":100,"lines":100,"statements":100}}' \
  --setupFiles "./jest/setup.js" \
  $1
